### ISSUE TITLE
Risks

### ISSUE THREAD

**Issue by rbodson1** [rbodson1/SWE-GraphicalPasswordAuthenticator#10]
Write down some risks that we have encountered so far, or might encounter in the future.

**Comment by paladmer** [comment]
[MPalad_RisksResearch.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6001499/MPalad_RisksResearch.txt)

technological risk

**Comment by TearRinse** [comment]
[RiskResearch.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6003577/RiskResearch.txt)
