### ISSUE TITLE
Final Conceptual Model

### ISSUE THREAD

**Issue by rbodson1** [rbodson1/SWE-GraphicalPasswordAuthenticator#11]
Final hand-drawn conceptual model

**Comment by Aaronportal465** [comment]
[https://app.zenhub.com/files/335695460/664d613c-39fe-455f-9056-c9079f83cadd/download](https://app.zenhub.com/files/335695460/664d613c-39fe-455f-9056-c9079f83cadd/download)

**Comment by Aaronportal465** [comment]
[https://app.zenhub.com/files/335695460/79b578b1-b6ea-4900-8b5d-75ab982f802f/download](https://app.zenhub.com/files/335695460/79b578b1-b6ea-4900-8b5d-75ab982f802f/download)


Final UML
