### ISSUE TITLE
User Interface Prototype

### ISSUE THREAD

**Issue by Aaronportal465** [rbodson1/SWE-GraphicalPasswordAuthenticator#12]

**Comment by rbodson1** [comment]
![Screen Shot 2021-03-03 at 8.35.57 PM.png](https://images.zenhubusercontent.com/5ffe8b47c28f5103dd605560/cf956269-a374-40fe-bf04-6195ae3f6a30)

However, I prefer my first suggestion if we were to choose between the two. It looks straight forward and not overly complicated to implement. Also the sequence diagram that I drew for the authentication process (check the Epic on Authentication Process UML) is based on my first suggested UI prototype.

I will explain the UI in the next meeting
