### ISSUE TITLE
2 UML Sequence Diagrams 

### ISSUE THREAD

**Issue by Aaronportal465** [rbodson1/SWE-GraphicalPasswordAuthenticator#14]
Two hand-drawn, UML sequence diagrams, each a distinct and different process in the application. (PM)
Each should have a minimum of three interacting objects (life lines) alternate sequences are encouraged.

**Comment by kwamito92** [comment]
Sequence Diagram of tile swapping. Not sure if correct but will explain the thought process in the next meeting.

![Graphic Puzzle Uml.jpg](https://images.zenhubusercontent.com/600718194d345310676492d3/cdbdae25-1dca-4c1f-80fd-d968011fbd48)

**Comment by paladmer** [comment]
![uml sequence 2 - tile movement](https://user-images.githubusercontent.com/48260594/111074670-7bc19600-84ba-11eb-8944-4f5407de0bca.jpg)

(I am not sure how "correct" it is) , but it is an attempt.  We can always discuss it later if need be!

I actually think we can use the same system objects if we want to - (UI , Backend, Database).  _We'll spin it like " These are the basic system components for an app to function. Like how in bio, there are "basic building blocks of life"._ 

I'm not sure how formal/informal the diagram needs to be. I kind of made a more broad/informal diagram.  His example from the video seems a little informal.  (Below Diagram)


![example - professor diagram uml 3 9 2021](https://user-images.githubusercontent.com/48260594/111074982-11a9f080-84bc-11eb-909d-7c4ff5d4659b.PNG)
