### ISSUE TITLE
2 UML Case Diagrams

### ISSUE THREAD

**Issue by Aaronportal465** [rbodson1/SWE-GraphicalPasswordAuthenticator#15]
Two hand-drawn, UML use case diagrams that are distinctly different . (SM)
Each has at a minimum of two actors and three inner objects/systems

**Comment by paladmer** [comment]
![MPalad_UseCase_RoughDraft](https://user-images.githubusercontent.com/48260594/110283317-e00dc280-7fad-11eb-8f7b-5cc7e9fcf752.png)

Some attempts at the use case (1 - User Log In).

**Comment by Aaronportal465** [comment]
UML Case Diagram: Tile Swap Password Creation Process
![image.png](https://images.zenhubusercontent.com/5ffc70266d34ee182103993d/7588ace9-a1ef-452d-9d36-66b7a0a0c577)

**Comment by Aaronportal465** [comment]
UML Case Diagram: Registration Process
![image.png](https://images.zenhubusercontent.com/5ffc70266d34ee182103993d/2fec8ea9-534d-409a-84af-8f11e00b086d)

**Comment by Aaronportal465** [comment]
Final Registration Process Use Case
![image.png](https://images.zenhubusercontent.com/5ffc70266d34ee182103993d/15535163-4168-4fc2-b924-4f26140788ea)

**Comment by Aaronportal465** [comment]
Final Image Scrambler Use Case
![image.png](https://images.zenhubusercontent.com/5ffc70266d34ee182103993d/fbb357b4-d47a-4597-8a43-32152e225eba)
