### ISSUE TITLE
Authentication Process UML Diagram

### ISSUE THREAD

**Issue by Aaronportal465** [rbodson1/SWE-GraphicalPasswordAuthenticator#16]
We each need to come up with a different UML diagram for the authentication process visualization for the app.

"Each should have a minimum of four interacting objects (life lines) alternate sequences are encouraged"
-Professor Johnson

[ UML Sequence ]
![image](https://user-images.githubusercontent.com/48260594/109925611-f6efa480-7c8f-11eb-9cbe-258f667ba6fe.png)

**Comment by rbodson1** [comment]
![Screen Shot 2021-03-03 at 8.35.14 PM.png](https://images.zenhubusercontent.com/5ffe8b47c28f5103dd605560/34f79e88-178e-4a8e-a9dd-3ad5db1cb812)

I will explain this UML in the next meeting.

**Comment by paladmer** [comment]
![MPalad_Draft_ Uml sequence_Authorization](https://user-images.githubusercontent.com/48260594/109924660-9f046e00-7c8e-11eb-966e-507e9551c7b3.png)

An attempt was made. This draft still needs some work. Discussion will be held in our meeting tomorrow.

**Comment by Jli421** [comment]
![1.jpg](https://images.zenhubusercontent.com/601ba71ec7e3476496ed0de2/f4ca3dc0-1f61-4ac2-9191-0385f7866d49)

**Comment by kwamito92** [comment]
![UML Auth.jpg](https://images.zenhubusercontent.com/600718194d345310676492d3/5abfc5a4-e28c-4375-8cce-820bc53e3f5d)

**Comment by Aaronportal465** [comment]
![image.png](https://images.zenhubusercontent.com/5ffc70266d34ee182103993d/038687ea-babd-4c4e-9a82-91df0d8d4500)

**Comment by TearRinse** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/60719739/109994971-d77e6900-7cdb-11eb-92c4-f0adbf7286ba.png)

Sorry for the lateness !!

**Comment by paladmer** [comment]
Version 1 and 2 are earlier iterations. After some group discussion, I made version 3 and 4. 

![UML_Sequence_Rough_1](https://user-images.githubusercontent.com/48260594/111021267-1de95d00-8399-11eb-8870-ac9be3f989d3.jpg)
![UML_Sequence_Rough_2](https://user-images.githubusercontent.com/48260594/111021274-29d51f00-8399-11eb-88a5-05294e74d71d.jpg)
![UML_Sequence_Rough_3](https://user-images.githubusercontent.com/48260594/111021279-2c377900-8399-11eb-8eb9-3bc226ed5ae5.jpg)
![UML_Sequence_Rough_4 final final](https://user-images.githubusercontent.com/48260594/111021281-2e99d300-8399-11eb-91d6-8136a213cb08.jpg)
