### ISSUE TITLE
Tile Movement UML Diagram

### ISSUE THREAD

**Issue by Aaronportal465** [rbodson1/SWE-GraphicalPasswordAuthenticator#17]
We each need to come up with a different UML diagram for the visualization of how the tiles can move and the password can be defined. 

"Each should have a minimum of four interacting objects (life lines) alternate sequences are encouraged"
-Professor Johnson
[ UML Sequence Diagram ]

**Comment by kwamito92** [comment]
![Graphic Puzzle Uml.jpg](https://images.zenhubusercontent.com/600718194d345310676492d3/fa2b346f-1cf9-452c-a25e-1debdb8700df)

Unsure of sequence graphical but will explain in next meeting the thought process
