### ISSUE TITLE
Development Setbacks Description

### ISSUE THREAD

**Issue by paladmer** [rbodson1/SWE-GraphicalPasswordAuthenticator#21]
(Scrum Master) 

"Describe the technology roadblocks, development setbacks, team collaboration problems, etc."

**Comment by paladmer** [comment]
[Development Setbacks Description.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6266045/Development.Setbacks.Description.txt)

Will write more later

**Comment by kwamito92** [comment]
[Setbacks.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6276052/Setbacks.txt)
