### ISSUE TITLE
Overall Purpose of the system & Intended Audience

### ISSUE THREAD

**Issue by paladmer** [rbodson1/SWE-GraphicalPasswordAuthenticator#24]
(Product Manager) 

Research.

"Introduce the overall purpose of the system and the target audience (user population (s))"

**Comment by paladmer** [comment]
[Overall Purpose of the system & Intended Audience.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6265591/Overall.Purpose.of.the.system.Intended.Audience.txt)

Might add more text later.

**Comment by kwamito92** [comment]
[https://app.zenhub.com/files/335695460/4e13ed66-166f-4e4d-a6cb-bd177379c674/download](https://app.zenhub.com/files/335695460/4e13ed66-166f-4e4d-a6cb-bd177379c674/download)

**Comment by kwamito92** [comment]
[Purpose & Audience]
(https://app.zenhub.com/files/335695460/3366fde4-1d93-410f-83e5-836e913ed710/download)

**Comment by kwamito92** [comment]
[Purpose & Audience.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6275915/Purpose.Audience.txt)
