### ISSUE TITLE
Goal of Project Description

### ISSUE THREAD

**Issue by paladmer** [rbodson1/SWE-GraphicalPasswordAuthenticator#25]
(Product Manager)

Explain clearly and fully the goal of your project as a solution your system solves for a problem

**Comment by paladmer** [comment]
[Goal of Product Description.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6265690/Goal.of.Product.Description.txt)

Will write more later.

**Comment by kwamito92** [comment]
[Goal Of Project.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/6275954/Goal.Of.Project.txt)
