### ISSUE TITLE
Research on Emulator (Android)

### ISSUE THREAD

**Issue by rbodson1** [rbodson1/SWE-GraphicalPasswordAuthenticator#4]
This epic is for every team member to investigate at least one android emulator that could be use for the app.

Write at least one paragraph about the emulator, its capabilities/advantages, disadvantages etc...We will then choose the best one.

This epic is assigned to all team members and has an estimation (weight) of 40. It is of a higher priority, so we will have at least a day to complete the task.

Please attach a text file of your emulator and your name. Don't close the issue until all have submitted.

The issue will be closed on Wednesday at 11:59pm

**Comment by kwamito92** [comment]
[kwame-Android Studio.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/5948033/kwame-Android.Studio.txt)

**Comment by paladmer** [comment]
[MPalad_AndroidStudio.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/5948713/MPalad_AndroidStudio.txt)

**Comment by rbodson1** [comment]
[https://app.zenhub.com/files/335695460/94bd291c-e1ec-4784-9b3c-eb110d9eb0e9/download](https://app.zenhub.com/files/335695460/94bd291c-e1ec-4784-9b3c-eb110d9eb0e9/download)

**Comment by rbodson1** [comment]
[Rachid-AndroidStudio.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/5957778/Rachid-AndroidStudio.txt)

**Comment by rbodson1** [comment]
[https://app.zenhub.com/files/335695460/8d8f1162-4f4d-426e-a30e-06bfc9e2e5bb/download](https://app.zenhub.com/files/335695460/8d8f1162-4f4d-426e-a30e-06bfc9e2e5bb/download)

**Comment by rbodson1** [comment]
[Rachid-AndroidStudio.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/5957796/Rachid-AndroidStudio.txt)

**Comment by Jli421** [comment]
[https://app.zenhub.com/files/335695460/5e3e0042-2936-4f64-953c-1d5c8a19b810/download](https://app.zenhub.com/files/335695460/5e3e0042-2936-4f64-953c-1d5c8a19b810/download)

**Comment by Jli421** [comment]
[Kris-AndroidStudio](https://app.zenhub.com/files/335695460/6b241bcd-4e40-4e08-b797-28917eba9655/download)

**Comment by Aaronportal465** [comment]
[https://app.zenhub.com/files/335695460/aaaf3de2-10f5-4a49-9092-48c89b5d927f/download](https://app.zenhub.com/files/335695460/aaaf3de2-10f5-4a49-9092-48c89b5d927f/download)

**Comment by TearRinse** [comment]
[Android Studio.txt](https://github.com/rbodson1/SWE-GraphicalPasswordAuthenticator/files/5966251/Android.Studio.txt)
