### ISSUE TITLE
Conceptual Model

### ISSUE THREAD

**Issue by rbodson1** [rbodson1/SWE-GraphicalPasswordAuthenticator#5]
This epic deals with having a **hand-drawn conceptual schema**  of what the app should be like.

![image.png](https://images.zenhubusercontent.com/5ffe8b47c28f5103dd605560/a3e6a0de-b01b-4eae-8040-af25c6c3fb09)
Use this image for a reference guild (cite: Dr. Johnson)

**Comment by paladmer** [comment]
![MPalad_ConceptualModelDraft-1](https://user-images.githubusercontent.com/48260594/107588509-d9b84080-6bd1-11eb-9054-e70352e977f2.jpg)

This is my attempt at the conceptual model. There were some other database choices such as MySQL or MongoDB. Once the team has solidified a database choice, we can then make changes to the model.

**Comment by rbodson1** [comment]
![image.png](https://images.zenhubusercontent.com/5ffe8b47c28f5103dd605560/e1af0d83-16f6-400c-9d89-8aaef6d009e6)

This is my attempted conceptual model.

**Comment by Jli421** [comment]
![image0.jpg](https://images.zenhubusercontent.com/601ba71ec7e3476496ed0de2/6c62b748-e980-45e3-bb8b-3bdebf62efcc)

**Comment by TearRinse** [comment]
![ConceptualModel](https://user-images.githubusercontent.com/60719739/107602274-f5820d80-6bf6-11eb-94f1-63be0cd39cdf.jpg)

Never used SQLite.....but i see two other responses included that so i wanted to go ahead and incorporate it into my model. Favoring a more PHP approach but wouldn't mind using a XML one.

**Comment by kwamito92** [comment]
![pic.jpg](https://images.zenhubusercontent.com/600718194d345310676492d3/21c92bdb-d881-41e0-a776-165a0a954b88)

Firebase database works well with android studio

**Comment by Aaronportal465** [comment]
![20210211_095120.jpg](https://images.zenhubusercontent.com/5ffc70266d34ee182103993d/c8102f59-3456-4f4b-8840-f11cee4b9273)

I'm in favor of using SQLite mostly cause I've used it once before with android studio and it's pretty easy to implement. I believe XML is the default format for flies in android studio, so it may be easier to keep it consistent rather than having to convert any files.
