### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by rbodson1** [rbodson1/SWE-GraphicalPasswordAuthenticator#6]
Research on the database to be used in the project.

Mainly assigned to PMs and SMs, however, programmers can join and post their researched databases as well.

This epic weighs 8 points.

**Comment by rbodson1** [comment]
[https://app.zenhub.com/files/335695460/bbd4e0dd-5676-4d7b-830a-8bb492280a6b/download](https://app.zenhub.com/files/335695460/bbd4e0dd-5676-4d7b-830a-8bb492280a6b/download)

**Comment by Jli421** [comment]
AWS database and Azure database are both suggested.

AWS is a cloud service offered by Amazon, and Azure is a cloud service offered by Microsoft. The bigness of these companies is the best proof of their trustness.

**Comment by Aaronportal465** [comment]
Potential database implementations could be MySQL and SQLite which are both very easy to implement and specifically in the case of SQLite provides a lightweight database that can easily be incorporated into the app.
